### ISSUE TITLE
Repozitorij za seminarsko nalogo

### ISSUE THREAD

**Issue by jaanos** [LukaFMF/PodatkovneBaze1#1]
Če ga s kolegom še nimata, svetujem, da za seminarsko nalogo naredita ločen repozitorij, ki naj bo tudi ustrezno poimenovan (npr. `Analiza-GitHub-repozitorija`). Ne pozabita tudi dodati povezave do njega na wiki na spletni učilnici.

**Comment by LukaFMF** [comment]
Sem naredil nov repozitorij in ga dodal v wiki.
